In [11]:
import numpy as np
#Notebook to test feature variance algorithms
def getVariance(featureMatrix):
        varValues = []
        for i in range(0, featureMatrix.shape[1]):
            values = featureMatrix[:,i]
            meanSample = np.mean(values)
            sumSample = 0
            for j in range(0, featureMatrix.shape[0]):
                sumSample += (featureMatrix[j,i] - meanSample)**2
            varValues.append(sumSample/(featureMatrix.shape[0] - 1))
        return varValues

In [12]:
def getHighVarFeatures(featureMatrix, numFeatures):
    varValues = getVariance(featureMatrix)
    featInds = np.argsort(varValues)[-numFeatures:]
    return featureMatrix[:,featInds]

In [17]:
#test1 
mat1 = np.matrix([[1,1,1],[3,2,2],[10,4,1]])
print(getHighVarFeatures(mat1,1))
#test2
print(getHighVarFeatures(mat1,2))
#test3
mat2 = np.matrix([[1,2,1],[1,2,2],[1,2,1]])
print(getHighVarFeatures(mat2,2))

[[ 1]
 [ 3]
 [10]]
[[ 1  1]
 [ 2  3]
 [ 4 10]]
[[2 1]
 [2 2]
 [2 1]]
